### PR TITLE
Test and fix nullHuman

### LINKED ISSUE #7: Problem in the wild observed with aligning human after hexen
```
prefix: "  "
```

```
    00: 7b22 6368 6563 6b73 756d 223a 3430 3833                                         {"checksum":4083
    20: 3137 3039 3236 2c22 6368 616e 6765 7322                                         170926,"changes"
    40: 3a5b 5d2c 2273 6f75 7263 6522 3a22 3130                                         :[],"source":"10
    60: 2e33 302e 3430 2e32 353a 3231 3330 3722                                         .30.40.25:21307"
    80: 7d                                       }
```

### PR DESCRIPTION
**Pull request by jcorbin**
Fixes #7 

cc @kriskowal

### CODE REVIEW

File: hex_transform.js [hunk 1]
```diff
@@ -72,7 +72,7 @@ HexTransform.prototype._finishLine = function finishLine() {
     var self = this;
     if (self.line.length) {
         var rem = self.screenOffset % self.cols;
-        if (rem !== 0 || self.nullHuman) {
+        if (rem !== 0 || (self.totalOffset === 0 && self.nullHuman)) {
```
Comment (kriskowal) [inline hex_transform.js:75]: Note that && binds more tightly than ||, so the parens are superfluous.

**Comment by kriskowal** [comment]
:ok:
